services:

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "25672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - fin_internal
      
  demo-api:
    build: ./PracticaRabbitMQ
    container_name: demo
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "32752:8080"
      - "32753:8081"
    networks:
      - fin_internal

volumes:
  rabbitmq_data:
  
networks:
  fin_internal:
    driver: bridge